### YamlMime:PythonClass
uid: azure.core.exceptions.ServiceResponseError
name: ServiceResponseError
fullName: azure.core.exceptions.ServiceResponseError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.AzureError
summary: 'The request was sent, but the client failed to understand the response.

  The connection may have timed out. These errors can be retried for idempotent or

  safe operations'
constructor:
  syntax: ServiceResponseError(message, *args, **kwargs)
  parameters:
  - name: message
methods:
- uid: azure.core.exceptions.ServiceResponseError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.ServiceResponseError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.ServiceResponseError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.ServiceResponseError.args
  name: args
