### YamlMime:PythonClass
uid: azure.core.exceptions.ResourceNotModifiedError
name: ResourceNotModifiedError
fullName: azure.core.exceptions.ResourceNotModifiedError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.HttpResponseError
summary: 'An error response with status code 304.

  This will not be raised directly by the Azure core pipeline.'
constructor:
  syntax: ResourceNotModifiedError(message=None, response=None, **kwargs)
  parameters:
  - name: message
    defaultValue: None
  - name: response
    defaultValue: None
methods:
- uid: azure.core.exceptions.ResourceNotModifiedError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.ResourceNotModifiedError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.ResourceNotModifiedError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.ResourceNotModifiedError.args
  name: args
- uid: azure.core.exceptions.ResourceNotModifiedError.error
  name: error
  signature: 'error: ODataV4Format | None'
- uid: azure.core.exceptions.ResourceNotModifiedError.model
  name: model
  signature: 'model: Any | None'
