### YamlMime:PythonClass
uid: azure.core.exceptions.ResponseNotReadError
name: ResponseNotReadError
fullName: azure.core.exceptions.ResponseNotReadError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.AzureError
summary: 'Error thrown if you try to access a response''s content without reading
  first.


  It is thrown if you try to access an ~azure.core.rest.HttpResponse or

  ~azure.core.rest.AsyncHttpResponse''s content without first reading the response''s
  bytes in first.'
constructor:
  syntax: ResponseNotReadError(response)
  parameters:
  - name: response
    description: The response that triggered the exception.
    isRequired: true
    types:
    - <xref:azure.core.rest.HttpResponse>
    - <xref:azure.core.rest.AsyncHttpResponse>
methods:
- uid: azure.core.exceptions.ResponseNotReadError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.ResponseNotReadError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.ResponseNotReadError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.ResponseNotReadError.args
  name: args
