### YamlMime:PythonClass
uid: azure.core.exceptions.HttpResponseError
name: HttpResponseError
fullName: azure.core.exceptions.HttpResponseError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.AzureError
summary: A request was made, and a non-success status code was received from the service.
constructor:
  syntax: HttpResponseError(message=None, response=None, **kwargs)
  parameters:
  - name: message
    description: HttpResponse's error message
    defaultValue: None
    types:
    - <xref:string>
  - name: response
    description: The response that triggered the exception.
    defaultValue: None
    types:
    - <xref:azure.core.pipeline.transport.HttpResponse>
    - <xref:azure.core.pipeline.transport.AsyncHttpResponse>
variables:
- description: The HTTP response reason
  name: reason
  types:
  - <xref:str>
- description: HttpResponse's status code
  name: status_code
  types:
  - <xref:int>
- description: The response that triggered the exception.
  name: response
  types:
  - <xref:azure.core.pipeline.transport.HttpResponse>
  - <xref:azure.core.pipeline.transport.AsyncHttpResponse>
- description: The request body/response body model
  name: model
  types:
  - <xref:msrest.serialization.Model>
- description: The formatted error
  name: error
  types:
  - <xref:azure.core.exceptions.ODataV4Format>
methods:
- uid: azure.core.exceptions.HttpResponseError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.HttpResponseError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.HttpResponseError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.HttpResponseError.args
  name: args
