### YamlMime:PythonClass
uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError
name: MSIAuthenticationTimeoutError
fullName: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError
module: msrestazure.azure_exceptions
inheritances:
- builtins.TimeoutError
- msrest.exceptions.ClientException
summary: If the MSI authentication reached the timeout without getting a token.
constructor:
  syntax: MSIAuthenticationTimeoutError()
methods:
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.args
  name: args
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.characters_written
  name: characters_written
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.errno
  name: errno
  summary: POSIX exception code
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.filename
  name: filename
  summary: exception filename
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.filename2
  name: filename2
  summary: second exception filename
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.strerror
  name: strerror
  summary: exception strerror
- uid: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError.winerror
  name: winerror
  summary: Win32 exception code
